### ISSUE TITLE
Cannot use Generic.Formatting.SpaceAfterNot

### ISSUE THREAD

**Issue by underdpt** [emielmolenaar/phpcs-laravel#11]
Hello,

Thanks for sharing your work, it's awesome and saved a lot of effort! :-)

I'm trying to use the rule `Generic.Formatting.SpaceAfterNot` to enforce a blank space after every NOT (`!`) but it seems to be clashing with this rule:

```xml
    <rule ref="Generic">
        <exclude-pattern>*.php</exclude-pattern>
        <exclude name="Generic.Strings.UnnecessaryStringConcat.Found)"/>
    </rule>
```

It seems this rule excludes all php files from the `Generic` ruleset, so no other rules under this ruleset would be enforced.

I'm not sure what this rule enfoces or why it's excluding all php files, maybe it can be modified somehow?

**Comment by emielmolenaar** [comment]
Thanks for bringing up this issue! I have been digging around on why these lines are in the ruleset, without any result. This set is a result of some work by [@nandosalles' ](https://medium.com/@nandosalles/the-ruleset-phpcs-for-my-laravel-projects-a54cb3c95b31) so most of the content is just a shameless copy-paste. It's weird that the whole Generic ruleset is disabled for all PHP files though. If I change that, all users of this ruleset will get very different results out of the blue to that does not have my preference. I might consider a new major version though.

Is there any way to create you own ruleset and extend this ruleset?

**Comment by underdpt** [comment]
Yeah, that's what I've doing, just using my own `phpcs.xml` importing your ruleset:

```xml
    <rule ref="./vendor/emielmolenaar/phpcs-laravel/ruleset.xml"/>
```

But I've just discovered `include-pattern` so I'm testing with this in my ruleset:

```xml
    <rule ref="Generic">
        <include-pattern>*</include-pattern>
        <exclude name="Generic.Strings.UnnecessaryStringConcat.Found"/>
    </rule>
```

And so far so good...

**Comment by emielmolenaar** [comment]
All right thanks for the feedback!
