### ISSUE TITLE
Remove warnings

### ISSUE THREAD

**Issue by josegus** [emielmolenaar/phpcs-laravel#7]
Nice ruleset, I'm learning how to use phpcs and I have a question:

how to remove this warnings?
![image](https://user-images.githubusercontent.com/13947849/99918532-ea050180-2ced-11eb-9849-1b6eb9a9df0d.png)

I'm checking this simple controller class. Also the class has some extra spaces that I wish it would be marked as error. See:
![image](https://user-images.githubusercontent.com/13947849/99918573-2cc6d980-2cee-11eb-8292-2114528fccd3.png)

As you can see, I want this extra spaces in my method to be marked as error

**Comment by G4Zz0L1** [comment]
I've the same problem, I think it's related to this https://github.com/sirbrillig/phpcs-import-detection/issues/35

I think the solution is to change the ruleset as they say in that issue.

**Comment by emielmolenaar** [comment]
The warnings are hard to fix, because of the fact that the inspector only knows about one file each time: https://github.com/sirbrillig/phpcs-import-detection/issues/37#issuecomment-594670725 .

Which spaces do you want to mark as error, you mean the newlines?

**Comment by G4Zz0L1** [comment]
I mean the Lavarel helpers like in this image. On the previous link I've quoted, the author suggest to use a global helper list to ignore those cases. Maybe we can do the same changing the ruleset, but I don't know where to find a complete list for all Laravel helpers.

![image](https://user-images.githubusercontent.com/13220636/101268722-e39f6c80-3766-11eb-9563-66c3ea46ee33.png)

**Comment by emielmolenaar** [comment]
Strictly, you should import these kind of functions like so:

```
use function env;
```

You might also ignore the warning for the next line by adding a comment and a rule to ignore:

```
// phpcs:ignore VariableAnalysis.CodeAnalysis.VariableAnalysis.UnusedVariable
```
