### ISSUE TITLE
Can you explain something?

### ISSUE THREAD

**Issue by fredbradley** [emielmolenaar/phpcs-laravel#8]
Hey - 

So I ran this and I got a lot of reports of "Found unimported symbol" they were all for group helper functions. EG. `url()`

Now I understand this line in the ruleset: https://github.com/emielmolenaar/phpcs-laravel/blob/2df10851ae4564179c9e5903c8caf19f8b82f394/ruleset.xml#L115

However why would it ask for those to be imported, when they are global methods/functions? Seems very counter intuitive if I have to add more and more exceptions to the rule? Am I not using it right?

**Comment by BenceSzalai** [comment]
I am puzzled by the same. Even `app()` triggers `Found unimported symbol` issue. It does not seem to be right or at least it is unlcear what the original intention with this rule? Are we supposed to not use these global methods? I mean it is arguable if they result in good architecture, but they are main part of Laravel and probably should not be flagged anyway.
